apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: '{{name}}-guestbook' # 'name' field of the Secret
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Navjot-S29/argocd-sample.git
        targetRevision: HEAD
        path: svcyaml
      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: test
